language: node_js
node_js:
- 10
script:
  - eval "$(ssh-agent -s)"
  - ssh-keyscan -H 195.124.186.19 >> ~/.ssh/known_hosts
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - npm run build-all
  - scp -r ./static/public/dist root@195.124.186.19:/home/kotyarich
before_install:
- openssl aes-256-cbc -K $encrypted_bfcd86c86eb2_key -iv $encrypted_bfcd86c86eb2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
